# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 155112901ed036038ba1397652989d158ad5bbdc6fbae44b37cdbe5e97fa8c051f60f6dc95c1662596009894b2acc5eea6db71e981a90d85c3a3152cc514e59a

test:
  secret_key_base: a8bf1b6b4aa8deaaa63e3a1a2813b61de6582c02ab8a384e7550462231114312ffdc4222c8f4551346e48be8f7c2ada9a5d6f654c07dea179e4b8d05792030f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
